import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/navbar";
import { Children } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Mene es main ek type define kar die .Or ek Object Bana dia {children :React.ReactNode} Ye ek 
// Object Hie 
type RootLayoutProps = { children :React.ReactNode;}

export default function RootLayout( { children} : RootLayoutProps) {

  return (
    <html lang="en"> 
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         {/* Layout jo hota hie wo sarie pages ko represent karta hie To main Es main jo 
         likonga wo mere pass sarie pages main show hoga To Mujhe navigation chahiye sarie 
         pages ke andar. To main <Navbar/> Ka teg laga donga {children} ke uper 
         To Sarie pages main navigation show hogaie*/}
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
